version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: viajuntos_api
    ports:
      - 5000:5000
    environment:
      SECRET_KEY: some_secret_in_env_variable
