export AIRSERVICE_JOBS_SECRET_KEY="mykey" 
export API_DEBUG="True"
export API_DOMAIN_NAME="http://localhost"  
export API_PORT=5000
export API_SECRET_KEY="myapisecretkey"
export DATABASE_URL="http://localhost:5432"  
export JWT_SECRET_KEY="myjwtkey"
export MAIL_PASSWORD="kdbbzkbkpemzfsrd"  
export MAIL_USERNAME="zjqtlwj@gmail.com"
export POSTGRES_DB="viajuntosdb" 
export POSTGRES_PASSWORD="password123"
export POSTGRES_PORT=5432
export POSTGRES_USER="viajuntos"
export SQLALCHEMY_DATABASE_URI="postgresql://viajuntos:password123@localhost:5432/viajuntosdb"
export DATABASE_URL="postgresql://viajuntos:password123@localhost:5432/viajuntosdb"
#echo $POSTGRES_PASSWORD