"""empty message

Revision ID: 224b8ff42c8c
Revises: d9fab9865480
Create Date: 2024-01-23 17:31:27.344316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224b8ff42c8c'
down_revision = 'd9fab9865480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('verification_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'verification_code')
    # ### end Alembic commands ###
