"""empty message

Revision ID: 2ea6f5560b2f
Revises: 224b8ff42c8c
Create Date: 2024-01-23 17:34:30.136743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea6f5560b2f'
down_revision = '224b8ff42c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'verification_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'verification_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
