"""empty message

Revision ID: 32059c4fa39e
Revises: 5e612479f8b6
Create Date: 2023-12-22 13:42:45.672507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32059c4fa39e'
down_revision = '5e612479f8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_posts', sa.Column('post_image_uris', sa.PickleType(), nullable=True))
    op.drop_column('event_posts', 'post_image_uri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_posts', sa.Column('post_image_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event_posts', 'post_image_uris')
    # ### end Alembic commands ###
