"""empty message

Revision ID: 3dcbf4c9bb65
Revises: 53d725ec338c
Create Date: 2023-10-21 21:44:39.445916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3dcbf4c9bb65'
down_revision = '53d725ec338c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.create_table('premium_expiration',
    sa.Column('user', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('expiration_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user')
    )
    op.add_column('chat', sa.Column('name', sa.String(), nullable=False))
    op.add_column('chat', sa.Column('type', sa.String(), nullable=False))
    op.add_column('chat', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint('chat_participant_id_fkey', 'chat', type_='foreignkey')
    op.drop_constraint('chat_creador_id_fkey', 'chat', type_='foreignkey')
    op.drop_constraint('chat_event_id_fkey', 'chat', type_='foreignkey')
    op.drop_column('chat', 'event_id')
    op.drop_column('chat', 'participant_id')
    op.drop_column('chat', 'creador_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('creador_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('chat', sa.Column('participant_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('chat', sa.Column('event_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('chat_event_id_fkey', 'chat', 'events', ['event_id'], ['id'])
    op.create_foreign_key('chat_creador_id_fkey', 'chat', 'users', ['creador_id'], ['id'])
    op.create_foreign_key('chat_participant_id_fkey', 'chat', 'users', ['participant_id'], ['id'])
    op.drop_column('chat', 'created_at')
    op.drop_column('chat', 'type')
    op.drop_column('chat', 'name')
    op.drop_table('premium_expiration')
    op.drop_table('members')
    # ### end Alembic commands ###
