"""empty message

Revision ID: 489e96848b60
Revises: 32059c4fa39e
Create Date: 2023-12-22 14:04:42.051174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '489e96848b60'
down_revision = '32059c4fa39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_posts', sa.Column('post_image_uri', sa.String(), nullable=True))
    op.drop_column('event_posts', 'post_image_uris')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_posts', sa.Column('post_image_uris', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('event_posts', 'post_image_uri')
    # ### end Alembic commands ###
