"""empty message

Revision ID: 50316437ba18
Revises: 98b678c9e3de
Create Date: 2023-11-12 19:16:48.957719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50316437ba18'
down_revision = '98b678c9e3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
