"""empty message

Revision ID: 592bcab4a452
Revises: 7ad0fd1e9db0
Create Date: 2025-01-26 12:46:23.229410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592bcab4a452'
down_revision = '7ad0fd1e9db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friend_invites', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friend_invites', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
