"""empty message

Revision ID: 5e612479f8b6
Revises: 6b7bc557f907
Create Date: 2023-12-22 04:04:57.615578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e612479f8b6'
down_revision = '6b7bc557f907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes_post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['event_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.add_column('event_posts', sa.Column('post_image_uris', sa.String(), nullable=True))
    op.alter_column('event_posts', 'event_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('event_posts', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('event_posts', 'likes')
    op.drop_column('event_posts', 'event_image_uri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_posts', sa.Column('event_image_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_posts', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('event_posts', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('event_posts', 'event_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('event_posts', 'post_image_uris')
    op.drop_table('likes_post')
    # ### end Alembic commands ###
