"""empty message

Revision ID: 6053b13aff11
Revises: af21941e0e2e
Create Date: 2025-01-16 23:18:19.753266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6053b13aff11'
down_revision = 'af21941e0e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('id_chat', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'friends', 'chat', ['id_chat'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_column('friends', 'id_chat')
    # ### end Alembic commands ###
