"""empty message

Revision ID: 68d399d874af
Revises: c70f334539ce
Create Date: 2024-01-26 18:20:48.715560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d399d874af'
down_revision = 'c70f334539ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'verificated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('verificated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
