"""empty message

Revision ID: 6b7bc557f907
Revises: 883126bbd15e
Create Date: 2023-12-22 02:26:05.259607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b7bc557f907'
down_revision = '883126bbd15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('event_image_uri', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['event_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_posts')
    # ### end Alembic commands ###
