"""empty message

Revision ID: 7ad0fd1e9db0
Revises: 6053b13aff11
Create Date: 2025-01-24 18:29:43.671187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ad0fd1e9db0'
down_revision = '6053b13aff11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_invites', sa.Column('invited', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('friend_invites', sa.Column('accepted', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'friend_invites', 'users', ['invited'], ['id'])
    op.drop_column('friend_invites', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_invites', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friend_invites', type_='foreignkey')
    op.drop_column('friend_invites', 'accepted')
    op.drop_column('friend_invites', 'invited')
    # ### end Alembic commands ###
