"""empty message

Revision ID: 7d19669838cf
Revises: 6a629059e589
Create Date: 2023-12-10 18:16:49.345176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d19669838cf'
down_revision = '6a629059e589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_free',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_free',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
