"""empty message

Revision ID: 883126bbd15e
Revises: bf0d0d336374
Create Date: 2023-12-14 01:35:46.257271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883126bbd15e'
down_revision = 'bf0d0d336374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.Enum('PUBLIC', 'FRIENDS', 'PRIVATE', name='eventtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###
