"""empty message

Revision ID: 98b678c9e3de
Revises: c11aaa289fc4
Create Date: 2023-11-12 19:10:17.517746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b678c9e3de'
down_revision = 'c11aaa289fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'image_url')
    # ### end Alembic commands ###
