"""empty message

Revision ID: a094bd6040bd
Revises: d177489ff27b
Create Date: 2023-12-22 14:27:19.586709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a094bd6040bd'
down_revision = 'd177489ff27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_images',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_image_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['event_posts.id'], name='post_images_post_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', name='post_images_pkey')
    )
    # ### end Alembic commands ###
