"""empty message

Revision ID: af21941e0e2e
Revises: 
Create Date: 2025-01-16 23:17:21.032317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af21941e0e2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'id_chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('id_chat', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
