"""empty message

Revision ID: bf0d0d336374
Revises: de3787c91758
Create Date: 2023-12-13 20:31:37.645692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0d0d336374'
down_revision = 'de3787c91758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_id')
    # ### end Alembic commands ###
