"""empty message

Revision ID: c11aaa289fc4
Revises: 3dcbf4c9bb65
Create Date: 2023-11-08 21:04:04.506376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c11aaa289fc4'
down_revision = '3dcbf4c9bb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('creator_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'chat', 'users', ['creator_id'], ['id'])
    op.add_column('events', sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'events', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'chat_id')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column('chat', 'creator_id')
    # ### end Alembic commands ###
