"""empty message

Revision ID: c215d08344fd
Revises: 592bcab4a452
Create Date: 2025-01-27 16:00:21.318106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c215d08344fd'
down_revision = '592bcab4a452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'datetime')
    # ### end Alembic commands ###
