"""empty message

Revision ID: c70f334539ce
Revises: 2ea6f5560b2f
Create Date: 2024-01-24 00:23:20.455473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70f334539ce'
down_revision = '2ea6f5560b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('verificated', sa.Boolean(), nullable=True))
    op.add_column('participant', sa.Column('time_verified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'time_verified')
    op.drop_column('participant', 'verificated')
    # ### end Alembic commands ###
