"""empty message

Revision ID: d177489ff27b
Revises: 489e96848b60
Create Date: 2023-12-22 14:23:47.695154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd177489ff27b'
down_revision = '489e96848b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_images',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_image_uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['event_posts.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.drop_column('event_posts', 'post_image_uri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_posts', sa.Column('post_image_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('post_images')
    # ### end Alembic commands ###
