"""empty message

Revision ID: d9fab9865480
Revises: ab569b332e98
Create Date: 2024-01-18 21:39:07.359464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9fab9865480'
down_revision = 'ab569b332e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_images',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('event_image_uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('events', 'event_image_uri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_image_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('event_images')
    # ### end Alembic commands ###
