"""empty message

Revision ID: de3787c91758
Revises: 289b6e80f133
Create Date: 2023-12-10 20:04:12.502811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3787c91758'
down_revision = '289b6e80f133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_event_free', sa.Boolean(), nullable=True))
    op.drop_column('events', 'event_free')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_free', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('events', 'is_event_free')
    # ### end Alembic commands ###
