"""empty message

Revision ID: f0eee8e0555d
Revises: 7d19669838cf
Create Date: 2023-12-10 19:05:05.796973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0eee8e0555d'
down_revision = '7d19669838cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('amount_event', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'amount_event')
    # ### end Alembic commands ###
